Update Revisions for CAM Module
BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem pull request #108
Opened 2024-05-27 11:12 UTC by Andrei-Matibag

**Overview**

-Updated Roles on Committee Table and Account Details
-Add Suffix on Admin Account Creation
-Fixed Modals for Delete Function in Committee Table

**Additional Information**
-Just a little more UI fixing to do
-The Committee Table's delete function is currently broken due to a missing recycling bin.

2024-05-30 09:51 UTC, Carl-Tabuso commented on src/account-details.php
Can you make the conditional statement for the allowed roles easier to read. For instance, you can approach it this way
```php
    if (!in_array($_SESSION['role'], $allowedRoles)) {
       header("Location: landing-page.php");
       exit();
    }
    include FileUtils::normalizeFilePath('submission_handlers/add-member.php');
``` 

Just making sure that this will not cause infinite redirection loop. Please change this or you may consider the suggestion above.

```php
        <?php
    } else {
        header("Location: landing-page.php");
    }
} else {
    header("Location: landing-page.php");
}
```

2024-05-30 09:56 UTC, Carl-Tabuso commented on src/manage-committee.php
Class attribute for your tables are missing a starting double quotation.
![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/ee9edc4e-0d5e-4197-b5f9-184c0414cfdc)

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/9ec7d875-11dd-4e19-be48-4fb8559a43b8)

2024-05-30 09:57 UTC, Carl-Tabuso commented on src/submission_handlers/add-member.php
what is this for?

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/dcb0178e-f786-48e3-a22b-1d1d05a24196)

2024-05-30 10:01 UTC, Carl-Tabuso requested changes
For `account-details.php` `admin-creation.php` `manage-committee.php`, can you make the conditional statement for the allowed roles easier to read. For instance, you can approach it this way.
```php
    if (!in_array($_SESSION['role'], $allowedRoles)) {
       header("Location: landing-page.php");
       exit();
    }
    include FileUtils::normalizeFilePath('submission_handlers/add-member.php');
``` 

Just making sure that this will not cause infinite redirection loop. Please change this or you may consider the suggestion above.

```php
        <?php
    } else {
        header("Location: landing-page.php");
    }
} else {
    header("Location: landing-page.php");
}
```

2024-05-30 10:18 UTC, Carl-Tabuso commented
Your admin creation page does not check if the user has selected a role before enabling the "Create Account" button.

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/2348da77-dd6f-4906-90a1-1f52d3679089

It also doesn't check if a user with the same email exists before/after hitting the "Create Account" button.

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/9a5a03e6-b80d-49dd-80d0-a4e0eba09bfb

2024-05-30 10:28 UTC, Carl-Tabuso commented
On line 223 in `manage-committee.php` 
```php
<th class="col-md-1 text-center fs-7 fw-bold spacing-5 checkbox-th">
    <input type="checkbox" name="selectedVoters[]" value="<?php echo $row["voter_id"]; ?>" class="voterCheckbox" style="display: none;">
</th>

``` 

You get this error upon checking the `error-logs.txt` file
```
2024-05-30 6:21 pm Error: [2] Undefined variable $row - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\manage-committee.php: 223
2024-05-30 6:21 pm Error: [2] Trying to access array offset on value of type null - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\manage-committee.php: 223
```

2024-06-02 02:34 UTC, Carl-Tabuso reviewed
Found issue: 

1. Submitting an existing email address outputs a JSON file content. 

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/1191531d-0fb9-4603-9db4-230ee8450497

This is due to `src/submission_handlers/add-members.php` file. This is not handled properly. We don't show/output such information.
```php
    if ($count > 0) {
        return ['status' => 'error', 'message' => 'This email already exists in the voter table.'];
    }
``` 

2. In your `src/scripts/member-form-validation.js`, github-advanced-security bot found an issue with your javascript regex and proposed recommendations for fixing it.

2024-06-02 11:15 UTC, Andrei-Matibag commented
Description:
The regular expressions for first_name, last_name, and middle_name was change into (?:\s[a-zA-Z]+). This regular expression uses a non-capturing group to match the optional whitespace and letters more explicitly, avoiding the potential for exponential backtracking.

Email Validation if exists or not
Server side message will show under the email input field after submit. This will be improve later on.

2024-06-02 11:19 UTC, Andrei-Matibag commented
@Carl-Tabuso I have committed the changes

2024-06-02 12:03 UTC, Carl-Tabuso commented on src/submission_handlers/add-member.php
> +                $emailError = 'Email already exists in the database.';
Refrain from mentioning anything technical such as the "database." Rephrase this next time.

2024-06-02 12:07 UTC, Carl-Tabuso approved these changes
You should add `error-reporting.php` file on the following files:

1. `account-details.php`
2. `admin-creation.php`
3. `manage-committee.php`
4. `add-member.php`
5. `manage-details.php`
6. `manage-members.php`

...but you can do this next time. I will just assign you an issue ticket. We can merge this now.

2024-06-02 12:09 UTC, merged