style: fixed the footer as well as its mobile counterpart
BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem pull request #134
Opened 2024-06-01 04:18 UTC by yojibeans

2024-06-01 05:17 UTC, Carl-Tabuso commented on src/about-us.php
> +            <p><a href="FAQ.php" class="footer-about-us"> FAQs | </a><a href="#" class="footer-about-us">Our Story</a></p>
`FAQ.php` file is not found. Use "#" this instead.

2024-06-01 05:21 UTC, Carl-Tabuso commented on src/landing-page.php
There was a duplication of copyright footer:

Code block from line 196-201
```html
<div>
  <img src="images/resc/iVOTE4.png" class="img-fluid ivote-logo" id="footer" alt="iVote Logo">
  <p>iVOTE is an Automated Election System (AES) for the student<br>organizations of the PUP Santa Rosa Campus.</p>
  <p class="credits-footer" id="credits"><span class="hello-text">© 2024 BSIT 3-1.</span> All Rights Reserved</p>
  <div class="vertical-line"></div>
</div>
```

Code block from line 236
```html
<p class="credits-footer" id="credits-two"><span class="hello-text">© 2024 BSIT 3-1.</span> All Rights Reserved</p>

```

2024-06-01 05:21 UTC, Carl-Tabuso requested changes
See comments

2024-06-03 06:55 UTC, yojibeans commented on src/landing-page.php
OH, we cannot directly move the 'credits' down at the very bottom. So instead, I duplicated it and set the duplicate as none during widescreens and when in mobile, the original will be displayed as none, and the duplicate will be displayed.

2024-06-06 11:35 UTC, Carl-Tabuso approved these changes
Changes were acknowledged

2024-06-06 11:36 UTC, Carl-Tabuso commented
@yojibeans  you have a merge conflict. Fix this before we proceed with merging.

2024-06-07 04:19 UTC, merged