feat: Modals: Maximum form cloning & Input image validation
BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem pull request #170
Opened 2024-06-14 07:02 UTC by hatdogguldo

2024-06-14 09:26 UTC, Carl-Tabuso commented
Assigning the review for this pull request to @biellamariscotes

2024-06-15 15:01 UTC, biellamariscotes requested changes
See comments in the codes.

2024-06-15 15:01 UTC, biellamariscotes commented on src/add-candidate.php
> +                            <div class="col-md-10 card-box mt-md-10" id="carl">
"carl"? Please provide a clearer, more descriptive name for the ID.

2024-06-15 15:01 UTC, biellamariscotes commented on src/add-candidate.php
> +                                        <img src="images/resc/warning.png" alt="Warning Icon">
Incorrect vector, do replace with [yellow-warning.png](https://drive.google.com/drive/folders/1H1Z7z9CHJZF_-jIwka9CoWR-DJYe34Cx?usp=sharing).

2024-06-15 15:01 UTC, biellamariscotes commented on src/add-candidate.php
> +                                        <p class="fw-bold fs-6 text-warning spacing-4 px-2">Maximum limit. You can only add up to 5 candidates at a time</p>
Have a title and a sub-title for this:

```
<p class="fw-bold fs-3 text-warning spacing-4">Maximum limit reached.</p>
<p class="fw-medium spacing-5">You can only add up to 5 candidates at a time.</p>
```

2024-06-15 15:10 UTC, biellamariscotes commented
In **Add Candidate**, attempting to add more than 2 results in failure and errors in error.log:


https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/11a73d55-9220-48dd-adae-31ca3ce60851

```
2024-06-15 10:28 pm Error: [8] session_start(): Ignoring session_start() because a session is already active - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\insert-candidates.php: 7
2024-06-15 10:28 pm Error: [2] Undefined array key "party_list" - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\insert-candidates.php: 19
2024-06-15 10:28 pm Error: [8192] trim(): Passing null to parameter #1 ($string) of type string is deprecated - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\insert-candidates.php: 19
2024-06-15 10:28 pm Error: [2] Undefined array key "election_year" - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\insert-candidates.php: 21
2024-06-15 10:28 pm Error: [8192] trim(): Passing null to parameter #1 ($string) of type string is deprecated - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\submission_handlers\insert-candidates.php: 21
```

It only submits the first form, and fails to successfully query the subsequent forms.

<hr>

Also, for the **X** mark on your forms, please re-style it to this:

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/e95bfd73-813a-4a0e-ba74-935c68fbddd0)

2024-06-18 02:36 UTC, hatdogguldo commented on src/add-candidate.php
> +                                        <p class="fw-bold fs-6 text-warning spacing-4 px-2">Maximum limit. You can only add up to 5 candidates at a time</p>
Noted

2024-06-18 02:36 UTC, hatdogguldo commented on src/add-candidate.php
> +                                        <img src="images/resc/warning.png" alt="Warning Icon">
Noted

2024-06-18 02:37 UTC, hatdogguldo commented on src/add-candidate.php
> +                            <div class="col-md-10 card-box mt-md-10" id="carl">
Noted

2024-06-19 09:30 UTC, biellamariscotes commented
Following up on this PR. Please address the requested changes as soon as possible. @hatdogguldo

2024-06-27 03:49 UTC, hatdogguldo commented
@biellamariscotes kindly disregard this [commit](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/commit/14fe1386083a0e99a3ea8d2532b5ebf0a8bbbca1). This should considered as new PR, not a commit for this pr.

2024-06-27 11:52 UTC, biellamariscotes approved these changes

2024-06-27 11:53 UTC, merged