Frontend of user-information-settings
BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem pull request #174
Opened 2024-06-16 13:07 UTC by Ivan-Edan

**Description:** This is PR is all about the Frontend of the User Settings Module which is the Information Page.

**Information Page**
- Added front end for this information settings
- Initial responsiveness
- Modals was inserted

**What's not yet integrated/Enhance:**
- the responsiveness needs to improve
- some padding and margin needs to adjust
- The iframe for the pdf needs to improved
- submit button in enter password needs to disable first
- some icons needs to change accurately
- Need to add backend
- Modals redirection

**Email Update page**
- Added front end design
- Initial responsiveness
- Modal when successful update of email

**What's not yet integrated/Enhance**
- green check vector on the email address text field
- the responsiveness needs to improve
- some padding and margin need to adjust
- Need to add Backend
- Proper modal connection/redirection

Sample Output:
![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162779484/8762041b-273f-47d1-8636-508692fbee00)

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162779484/402ce56c-f2d1-4ecc-935c-0354c0a17c95)

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162779484/b3fab600-e102-4700-a538-ed1ec6272294)

2024-06-16 14:25 UTC, Carl-Tabuso commented
This is mostly frontend so I think we should get the inputs of @biellamariscotes

2024-06-18 02:52 UTC, Andrea-Villalobos reviewed
- On my device with zoom level of 100%, this is what it looks like:
![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162780943/eb959316-6f9b-40cf-bb7d-c5da781866c0)
The containers' length are not equal. Some paddings are a bit off. 
Looks crowded.

- Missing href links in the side navigation panel/section.

- The eye toggle for password is missing.
![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162780943/a90e7c42-dcbf-43be-b364-8d535fafd384)
- It seems that the check gif is not centered, it looks like it is placed a little bit to the left. I am not sure though.
- I cannot also dismiss this modal using the close/X button.

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162780943/e34a8e8a-b82f-4eac-a6e6-833edb1e4ec0)

- I am suggesting that we use the same css file named user-settings.css so we can make the containers uniform. Please see my transfer org page.  Or do you have any idea/s on how can we make it uniform without having conflicts in the css?

2024-06-18 18:58 UTC, Ivan-Edan commented
Already change the style of the container using the template of transfer org made by @Andrea-Villalobos

2024-06-18 19:32 UTC, Ivan-Edan commented
Already fix the redirection/linking of the pages in settings module and also renamed the file of transfer-org.php -> user-setting-transfer.php for consistency of the other parts of the setting module.

Review required: @Andrea-Villalobos

2024-06-19 09:35 UTC, biellamariscotes commented
There seems to be a conflict with the development branch. Please address it first before I can review your changed files. Thank you! @Ivan-Edan

2024-06-27 03:49 UTC, biellamariscotes requested changes
Please read the comments.

2024-06-27 03:49 UTC, biellamariscotes commented on src/includes/components/topnavbar.php
>          <li><a class="dropdown-item" href="voter-faqs.php"><span class="main-color pe-3"><i data-feather="help-circle"></i></span>FAQs</a></li>
There's a duplication here. Please remove the extra links.

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/52904c65-748a-4138-828a-0d7bb8fd6850)

2024-06-27 03:49 UTC, biellamariscotes commented on src/setting-email-update.php
> +    <link rel="stylesheet" href="<?php echo '../src/styles/orgs/' . $org_acronym . '.css'; ?>">
There is an absence of main styles component here: `style.css `and `core.css`

2024-06-27 03:50 UTC, biellamariscotes commented
Based on my comment on lines +34 to +38, there is an issue with the footer.

Since the footer's front-end relies on the style.css and core.css, I tried applying these styles on my end. However, it is not properly rendering, and this is because of the conflicts between duplicate classes in the main style components and the file's own styles. See the outcome below:

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/8265d3fe-6210-4ecf-be49-883589848a17)

Kindly tell me if you guys will apply your own style of the footer (but this should look identical to the admin side's footer) or fix the conflicting styles.

2024-06-27 04:25 UTC, biellamariscotes commented
Will merge this now. As what we've agreed on in our conversion (f2f), the responsiveness of the footer shall be resolved on the next PR. Thanks!

2024-06-27 04:26 UTC, biellamariscotes approved these changes

2024-06-27 04:28 UTC, merged