Added backend to the user password reset in settings
BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem pull request #278
Opened 2024-07-17 10:44 UTC by Ivan-Edan

Description: This PR is the continuation of applying functions in the settings page for the reset password module.

**Additional Notes:**
- Added Backend Functionality
- Fix the bug encountered in the final defense such as the margin of the error message and the visibility of the eye toggle in the settings password input field.

2024-07-17 10:52 UTC, Carl-Tabuso commented on src/includes/process-user-password.php
> +require_once FileUtils::normalizeFilePath(__DIR__ . '/classes/session-manager.php');
You don't need this file.

2024-07-17 10:53 UTC, Carl-Tabuso commented on src/includes/process-user-password.php
> +require_once FileUtils::normalizeFilePath(__DIR__ . '/classes/session-manager.php');
You don't need this file.

2024-07-17 11:05 UTC, Ivan-Edan commented
Address the requested changes

2024-07-18 04:43 UTC, Carl-Tabuso commented on src/user-setting-password.php
You have way too many duplicates of stylesheets and unnecessary scripts from the head element to the body tag.

Check this closely:

```html

<head>
<!--some metadatas-->

        <!-- Montserrat Font -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
        <!-- Fontawesome CDN Link -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
        <!-- Bootstrap 5 code -->
        <link type="text/css" href="../vendor/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="styles/loader.css" />
        <link rel="stylesheet" href="styles/user-setting-password.css" />
        <link rel="stylesheet" href="<?php echo '../src/styles/orgs/' . $org_acronym . '.css'; ?>">
        <!-- Icons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
        <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>
<!-- HTML codes -->

        <script src="../src/scripts/feather.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybBogGz5D6306zI1M1rEM0bzW2UN4u5d1a2KX9KRALhWV4aKN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cu5eC5sE/PZz57f5mlP34fIuFj0m9koW2j4X0eY9Fzj5sy9F2YfGOFlUNcr4fnfM" crossorigin="anonymous"></script>
        <script src="../vendor/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="scripts/change-password.js"></script>
        <script src="scripts/loader.js"></script>
</body>

```

You have these following issues:

- Conflicting versions of jQuery — we are using the 3.7.1 version.
- Duplicates of font-awesome library CDN
- **Usage of bootstrap CDN**: Why do you have to load the `bootstrap.min.js` twice and with different versions, as well as `popper.min.js`?  These are all already included in our local resources of ` <script src="../vendor/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>`
- **Proper decomposition**: Separate your javascript codes into a separate js file. This will be hard to read and maintain in the long run.

2024-07-18 04:48 UTC, Carl-Tabuso commented on src/user-setting-password.php
Issues that could arise from these are:

- Increased load times due to redundancy.
- Version conflicts since you're loading bootstrap both on local and from CDN.
- Caching Issues due to same source is requested from different URLs.
- Hard to maintain and debug due to duplicate of scripts.
- Duplicate functionality and style rendering issue.

2024-07-18 05:22 UTC, Carl-Tabuso commented on src/setting-password-reset.php
The remarks on `user-setting-password.php` are also applicable here.

2024-07-18 05:38 UTC, Carl-Tabuso commented on src/includes/process-user-password.php
Apart from this doesn't work, it also doesn't include the "sco" database to update the user's password.

2024-07-18 05:38 UTC, Carl-Tabuso requested changes
The password reset is not working as intended. You have a security issue for showing the entered password in the browser's URL. Check your UI designs, the eye toggle is missing on the password input field but is layout properly on the Confirm Password field. 

https://github.com/user-attachments/assets/8a77ce85-83ec-4d8b-aca6-0851f7d99031

2024-07-19 15:02 UTC, Ivan-Edan commented
Fix the settings as follows added red border in the input field if the user input incorrect password:
![image](https://github.com/user-attachments/assets/6be6a327-a915-4ce3-beda-aea85ae5a3fe)
Fix the eye toggle missing in text field:
![image](https://github.com/user-attachments/assets/a6b192ce-e4ca-4da4-b760-1356e6c8b61b)



the modal timer will be implemented in the next pr.

2024-07-21 11:41 UTC, Ivan-Edan commented
Added features in the reset password such as:

- Modal redirection to landing page

- Countdown timer once the user changes their password.

2024-07-23 14:18 UTC, Carl-Tabuso commented on src/setting-password-reset.php
There are still duplicates in your code.

Fontawesome CDN
```html
        <!-- Fontawesome CDN Link -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
        <!-- Icons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
```

feather-icons CDN and local
```html
<script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
<script src="../src/scripts/feather.js"></script>
```

Use the locally installed one.

And can you please indent your code properly.

![image](https://github.com/user-attachments/assets/cbbb2cd1-934d-4e4a-b7be-4c04ca3921d8)

2024-07-23 14:21 UTC, Carl-Tabuso commented on src/user-setting-password.php
feather-icons CDN and local

```html
<script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
<script src="../src/scripts/feather.js"></script>
```

You can remove the `<script src="../vendor/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>` it is unncessary because you already have the bundle.
```html
        <script src="../vendor/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="../vendor/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
```

2024-07-23 14:22 UTC, Carl-Tabuso requested changes
It'll be useless for anybody to test this if issues on code-level can be easily spotted.

2024-07-25 07:31 UTC, Ivan-Edan commented
Already updated the code and remove the requested links and added indentation to the code

2024-07-25 15:06 UTC, Carl-Tabuso requested changes
`setting-password-reset.php`
```html
<head>
  <!--- metas, stylesheets, etc. -->

  <script src="../src/scripts/feather.js"></script>
</head>

<body>
  <!--- HTML codes -->

   <script src="../src/scripts/feather.js"></script>
  <!--- other scripts -->
   <script src="scripts/loader.js"></script>
   <script src="scripts/loader.js"></script>
</body>
``` 

You have duplicate of loader and feather scripts. Also, i don't quite understand why do you have to traverse so far as to go back from the root folder and then do this `../../` You're already at the `src` folder, you can simply just do it like this:
```html
<script src="scripts/feather.js"></script>
```

On `user-setting-password.php`
```html
<head>
  <!--- metas, stylesheets, etc. -->

  <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
</head>

<body>
  <!--- HTML codes -->

   <script src="../src/scripts/feather.js"></script>
  <!--- other scripts -->
</body>
```

You can just remove the CDN script of the feather because you have it already in your body.

Can you please also decide where you want to put your script files? Some are in head and others are within the body.

2024-07-27 04:40 UTC, Ivan-Edan commented
Already addressed the requested changes.

2024-07-28 03:58 UTC, Carl-Tabuso commented
> Already addressed the requested changes.

Can you provide a demo?

2024-07-28 04:08 UTC, Carl-Tabuso reviewed
I suggest moving all your scripts within the head of your files.

2024-07-28 04:08 UTC, Carl-Tabuso commented on src/setting-password-reset.php
> +            </script>
What is the purpose of this code? From what I understood, this is supposed to show a success email  modal after successful password changed. But there's no API/endpoint calls to validate the submitted password to the server-side?

Also, as far as I can remember, this page serves as a medium for the user to change his password?

2024-07-30 03:40 UTC, Ivan-Edan commented
Sample Demo of changing the password:
[Screen Recording - Made with FlexClip.webm](https://github.com/user-attachments/assets/48a08b49-e916-46ad-99eb-6d44d4357322)

2024-08-01 09:03 UTC, Carl-Tabuso approved these changes

2024-08-01 09:04 UTC, merged