Remove COR related and fix error when backing a page
BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem pull request #307
Opened 2024-08-01 15:23 UTC by Andrea-Villalobos

updated information page

![Screenshot 2024-08-01 222936](https://github.com/user-attachments/assets/1deb8732-fe0f-4f4f-bcea-d8f381fbf2f3)

updated transfer org, removed the cor

proof of testing:

https://github.com/user-attachments/assets/97f7f33a-2892-440c-a7d8-51256cb3489e

fix error when user tries to back in the browser upon logging in
the page redirections still works

proof of testing:

https://github.com/user-attachments/assets/80c414be-24bf-424b-aa69-0df902120714

https://github.com/user-attachments/assets/8e047795-c73f-4860-b1ce-52c46b40a115

https://github.com/user-attachments/assets/31be4b52-1296-4a2b-817a-4dca77100755

2024-08-01 15:43 UTC, Carl-Tabuso commented on src/ballot-forms.php
Do remove these two scripts.


There already a script linking to a locally installed `feather.js` on line 454

![image](https://github.com/user-attachments/assets/0f723237-75be-49b6-bd89-7a100d931ed7)


You don't need the CDN of bootstrap.js because you already have the bundle.min.js on line 456

![image](https://github.com/user-attachments/assets/59f243f1-89a0-4529-a392-b8196e0cdc1a)

2024-08-01 15:46 UTC, Carl-Tabuso commented on src/end-point.php
Be consistent with the script plugins. Use `<script src="scripts/feather.js"></script>` instead. If you're including it within the head element, use `defer` attribute.

2024-08-01 15:48 UTC, Carl-Tabuso commented on src/user-setting-information.php
Same issue with the `ballot-forms.php` but here you have a duplicate of jquery with conflicting versions.

![image](https://github.com/user-attachments/assets/2a3c56f1-d758-4d27-9a64-2d17b68f85fe)

![image](https://github.com/user-attachments/assets/5f6559e4-80e6-4d20-bd70-2388f6058f09)

2024-08-01 15:48 UTC, Carl-Tabuso commented on src/user-setting-transfer.php
![image](https://github.com/user-attachments/assets/f75b736f-0afc-411d-adf7-ce7dff0581dc)

2024-08-01 15:50 UTC, Carl-Tabuso requested changes
- Check comments for each file.

- Use the 3.7.1 version of jQuery in all your files.

2024-08-01 16:11 UTC, Andrea-Villalobos commented on src/ballot-forms.php
cannot remove the cdn feather script 
the local feather.js has feather.replace(); script only, not the feather library
![Screenshot 2024-08-02 000013](https://github.com/user-attachments/assets/d8126276-d404-4489-a249-e78b69f60645)

2024-08-02 11:42 UTC, Carl-Tabuso reviewed
I still get a server error due to many redirections. I tried going back to the login page after successful logged-in. And another, is accessing the page, if for example, it was accidentally closed. I suspect this is also the case for ballot forms, endpoints, etc. upon successful login.

https://github.com/user-attachments/assets/05a3064c-e66e-4bf4-843d-476700a28434

2024-08-03 04:21 UTC, Andrea-Villalobos commented
> I still get a server error due to many redirections. I tried going back to the login page after successful logged-in. And another, is accessing the page, if for example, it was accidentally closed. I suspect this is also the case for ballot forms, endpoints, etc. upon successful login.
> 
>  2024-08-02.19-38-05.mp4

I assumed that you have a null value in the voter_status. Kindly try again. Thank you.

2024-08-03 14:32 UTC, Carl-Tabuso commented
> I assumed that you have a null value in the voter_status. Kindly try again. Apologies for the late response. Thank you.

 Due to the massive changes in how accounts are created and set up, having a voter status was deemed unnecessary and obsolete.

2024-08-04 03:49 UTC, Andrea-Villalobos commented
The conflict has been resolved. Thank you.

2024-08-04 04:27 UTC, Carl-Tabuso commented
> The conflict has been resolved. Thank you.

Still won't work.  I get this error on the log file thrice, upon accessing the transfer page and page 2, as well as submitting the transfer form.

```
2024-08-04 12:23 pm Error: [2] Undefined array key "student_number" - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\user-setting-transfer.php: 182
```

Student number is not displayed.
![image](https://github.com/user-attachments/assets/c1e9e2f5-9d77-48a2-b816-21c5a28f577d)

2024-08-04 04:29 UTC, Carl-Tabuso commented
You're not supposed to check for `voter_status` anymore. This field was already removed from the table because it serves no purpose.  Another, what we do have is `student_id` not `student_number` field in the voter table.

2024-08-04 06:19 UTC, Carl-Tabuso commented
Is this working now?

2024-08-04 08:43 UTC, Andrea-Villalobos commented
> Is this working now?

Yes.

Proof of Testing:

https://github.com/user-attachments/assets/3336e2e5-e3cd-4286-9cd1-6e97314828c7

2024-08-04 08:48 UTC, Carl-Tabuso commented
Unfortunately, this is how it goes on my end. I can't seem to figure out what's the problem.


https://github.com/user-attachments/assets/b830e106-f1c1-4a7d-84b7-49adc2e0ffb9

2024-08-04 09:17 UTC, Carl-Tabuso approved these changes
I'll check if this works fine on the live version. I'm not quite sure if the issue is only on my end.

2024-08-04 09:18 UTC, merged