feat: AT4-44 added backend to display data from database according to…
BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem pull request #37
Opened 2024-04-20 23:06 UTC by AraojoBenedict

- added session
- added backend to display data from the database according to position
- functional filter button to display the chosen position
- added sorting from highest to lowest on each position
- fixed style path
- commented the script that add candidate card

2024-04-21 01:54 UTC, Carl-Tabuso commented
Your branch is outdated. Kindly rebase it to fetch the latest changes from base branch development.

2024-04-21 04:18 UTC, AraojoBenedict commented
Successfully rebased and updated refs/heads/AT4-44.

2024-04-21 13:27 UTC, Carl-Tabuso commented
Earlier, I was talking about your head branch being outdated. I am requesting you once again to rebase your head branch from the development branch before we proceed with the merging.

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/569ebd56-b701-4f72-8f41-64d48abec53d)

2024-04-21 14:32 UTC, Carl-Tabuso requested changes
Your code is quite hard to understand because some are not indented properly. There are also too much linebreaks from one line of code to another. See images below.

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/ebb5d7ce-ccdd-4772-974c-60dc460208ba)
![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/7c797325-26f1-46b0-806c-22eace8c88f8)
![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/4da18087-0e04-43df-b607-bbc3fd662fc5)

Your SQL queries are also of procedural types. In OOP PHP, we are mostly using the arrow notation (->) instead of the dot (.) one. Let's be consistent with how we work on the server-side and make sure we adhere to what has been decided by the development team.

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/71dc2143-c4cb-4173-8e47-02f49e5180d3)
![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/7af3edc4-9b55-4777-b42f-502270f95517)
![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/79cd4660-f673-4fbd-97ce-1e1c04802722)

May i also request for an SQL file i can import in phpmyadmin so i can further explore and test your code before we get into merging.

2024-04-23 13:47 UTC, AraojoBenedict commented
[SQL File.txt](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/files/15077755/SQL.File.txt)

2024-04-23 15:18 UTC, Carl-Tabuso commented on src/result-generation.php
> +     <?php
properly indent this next time.

2024-04-23 15:19 UTC, Carl-Tabuso commented on src/result-generation.php
> +                    $vote_count_query = "SELECT COUNT(*) as vote_count FROM vote WHERE candidate_id = $candidate_id";
Use prepared sql statements next time. This is to avoid possible SQL injections to you r code.

2024-04-23 15:20 UTC, Carl-Tabuso approved these changes
See the comments and make sure to address them as fix type next time.

2024-04-23 15:20 UTC, merged