Updates on CAM Module
BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem pull request #57
Opened 2024-04-29 06:20 UTC by Andrei-Matibag

**Overview**

- Updated UI of Admin Creation.
- Creation of UI and Back-end of Committee Table.

**Additional Information**

- Back-end of Admin Creation is in progress.
- There is a problem in the footer in Committee Table.
- There is a problem in sidebar when the page is on Admin Creation.
- Responsiveness and Back-end of Account Details is in progress.

2024-04-29 06:22 UTC, Andrei-Matibag commented
**Additional**

- manage-members.php
-This code allows only the verified accounts of committee/admin member to show on table and it will only show the accounts that has the role of committee member and admin member only.

2024-04-29 11:33 UTC, C-Ivan-Bandilla requested changes

2024-04-29 11:33 UTC, C-Ivan-Bandilla commented on src/admin-creation.php
> +require_once 'includes/session-handler.php';
Kindly use the `normalizeFilepath` function for **includes** and **requires**

Here is the sample
![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/92857477/f31202a7-3f8d-4859-a2ea-49942a4fd909)

the function is available if you include the file utility `class include_once str_replace('/', DIRECTORY_SEPARATOR, 'includes/classes/file-utils.php');` _**file path may vary**_

The purpose is that we are not sure of what operating system our website would be hosted. The operating system varies on directory separators read more [here](https://en.wikipedia.org/wiki/Path_(computing)#:~:text=paths%20are%20appended.-,Representations%20of%20paths%20by%20operating%20system%20and%20shell,-%5Bedit%5D)
This function appropriately assigns the correct directory separator for the current OS. It's better to be safe thank you.

2024-05-01 02:19 UTC, Carl-Tabuso commented on src/submission_handlers/manage-members.php
> +$query = "SELECT * FROM voter WHERE status = 'For Verification'";
Use prepared statement. Your query is susceptible to SQL injection.

2024-05-01 02:19 UTC, Carl-Tabuso requested changes
Check comments and do the necessary changes.

2024-05-01 10:37 UTC, Carl-Tabuso commented on src/admin-creation.php
> +if (isset($_SESSION['voter_id'])) {
You're not checking if the user role is set to Committee Member.

2024-05-01 10:39 UTC, Carl-Tabuso commented on src/manage-committee.php
> +require_once 'includes/classes/session-manager.php';
You only require the session manager if your page is static. Remove this.

2024-05-01 10:39 UTC, Carl-Tabuso commented on src/manage-committee.php
> +if (isset($_SESSION['voter_id'])) {
You don't check for the role of the user.

2024-05-01 10:41 UTC, Carl-Tabuso requested changes
Your code is prone to URL directory listing. And the same as before, some of your files that require files from another folder or directory are not normalized. See comments below.

2024-05-02 04:02 UTC, Andrei-Matibag commented
The changes has been made

2024-05-03 02:57 UTC, Carl-Tabuso requested changes
This is such a redundancy. You can check the codes of admin dashboard on how it implements role checking.

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/25e5695d-423d-4e04-9ee2-1b52dba9d402)

2024-05-03 03:02 UTC, Carl-Tabuso approved these changes
We'll get back on this issues you are yet to address in  your next PR.

2024-05-03 03:03 UTC, merged